import type { TbDataKey } from '../types';
import type { NativeOptions, NativeSeriesSettings } from './nativeWidgetTypes';

/** Defaults are applied to a copy; false, zero and unknown extension fields survive editing. */
export function withNativeSettings(options: NativeOptions) {
  const copy: NativeOptions = JSON.parse(JSON.stringify(options));
  return {
    ...copy,
    presentation: {
      layout: 'vertical' as const,
      labelPosition: 'top' as const,
      showValue: true,
      labelFontSize: 12,
      labelColor: '#bcd0df',
      valueColor: '',
      dateFormat: 'locale' as const,
      ...copy.presentation,
    },
    chart: {
      axes: [{ id: 'default', label: '', position: 'left' as const, min: null, max: null }],
      stack: false,
      dataZoom: false,
      legendPosition: 'top' as const,
      tooltip: true,
      animation: false,
      thresholds: [],
      ...copy.chart,
    },
    table: {
      search: false,
      showTimestamp: true,
      stickyHeader: false,
      pagination: true,
      pageSize: 20,
      sortOrder: 'desc' as const,
      ...copy.table,
    },
    progress: {
      direction: 'horizontal' as const,
      showTicks: false,
      trackColor: 'rgba(200,220,255,.12)',
      ...copy.progress,
    },
    gauge: {
      type: 'radial' as const,
      startAngle: 225,
      endAngle: -45,
      splitNumber: 10,
      showTicks: true,
      showPointer: true,
      width: 8,
      ...copy.gauge,
    },
    pie: {
      innerRadius: 0,
      showPercent: false,
      showTotal: false,
      totalLabel: '合计',
      totalDecimals: 0,
      totalUnits: '',
      clockwise: true,
      ...copy.pie,
    },
    latestBar: { horizontal: false, min: null, max: null, barWidth: 40, showAxisLabels: true, ...copy.latestBar },
    range: { fillOpacity: 0.7, outOfRangeColor: '#ccc', showBoundaries: true, ...copy.range },
    state: {
      includePrevious: true,
      extendToEnd: true,
      states: [
        { label: 'Off', value: 0, sourceType: 'constant' as const, sourceValue: false },
        { label: 'On', value: 1, sourceType: 'constant' as const, sourceValue: true },
      ],
      ...copy.state,
    },
    battery: {
      layout: 'vertical_solid' as const,
      sectionsCount: 4,
      showValue: true,
      autoScaleValueSize: true,
      valueFontSize: 20,
      valueColor: { color: '#eaf5ff', ranges: [] },
      batteryLevelColor: {
        color: '#e0e0e0',
        ranges: [
          { from: null, to: 25, color: 'rgba(227,71,71,1)' },
          { from: 25, to: 50, color: 'rgba(246,206,67,1)' },
          { from: 50, to: null, color: 'rgba(92,223,144,1)' },
        ],
      },
      batteryShapeColor: {
        color: 'rgba(224,224,224,.32)',
        ranges: [
          { from: null, to: 25, color: 'rgba(227,71,71,.32)' },
          { from: 25, to: 50, color: 'rgba(246,206,67,.32)' },
          { from: 50, to: null, color: 'rgba(92,223,144,.32)' },
        ],
      },
      padding: 12,
      ...copy.battery,
    },
    signal: {
      layout: 'wifi' as const,
      showDate: false,
      dateFormat: 'relative' as const,
      dateFontSize: 12,
      dateColor: '#bcd0df',
      activeBarsColor: {
        color: 'rgba(92,223,144,1)',
        ranges: [
          { from: null, to: -85, color: 'rgba(227,71,71,1)' },
          { from: -85, to: -70, color: 'rgba(255,122,0,1)' },
          { from: -70, to: -55, color: 'rgba(246,206,67,1)' },
          { from: -55, to: null, color: 'rgba(92,223,144,1)' },
        ],
      },
      noSignalRssiValue: -100,
      inactiveBarsColor: 'rgba(224,224,224,1)',
      showTooltip: true,
      showTooltipValue: true,
      tooltipValueFontSize: 13,
      tooltipValueColor: '#eaf5ff',
      showTooltipDate: true,
      tooltipDateFormat: 'relative' as const,
      tooltipDateFontSize: 13,
      tooltipDateColor: '#bcd0df',
      tooltipBackgroundColor: 'rgba(19,35,51,.85)',
      tooltipBackgroundBlur: 3,
      padding: 12,
      ...copy.signal,
    },
    wind: {
      layout: 'default' as const,
      centerValueFontSize: 24,
      centerValueColor: { color: '#eaf5ff', ranges: [] },
      ticksColor: 'rgba(224,224,224,.16)',
      directionalNamesElseDegrees: true,
      majorTicksColor: '#a7bed1',
      majorTicksFontSize: 14,
      minorTicksColor: '#879eae',
      minorTicksFontSize: 14,
      arrowColor: '#eaf5ff',
      backgroundType: 'color' as const,
      backgroundColor: '#fff',
      backgroundImage: '',
      overlayEnabled: false,
      overlayColor: 'rgba(255,255,255,0.72)',
      overlayBlur: 3,
      padding: 12,
      ...copy.wind,
    },
    rpcButton: {
      methodName: 'rpcCommand',
      methodParams: '{}',
      requestTimeout: 5000,
      oneWayElseTwoWay: true,
      buttonText: 'Send RPC',
      ...copy.rpcButton,
      styleButton: { isRaised: true, isPrimary: false, bgColor: null, textColor: null, ...copy.rpcButton?.styleButton },
    },
    control: {
      kind: 'switch' as const,
      title: '',
      initialValue: false,
      retrieveValueMethod: 'rpc' as const,
      valueKey: 'value',
      attributeScope: 'SERVER_SCOPE' as const,
      getValueMethod: 'getValue',
      setValueMethod: 'setValue',
      requestTimeout: 5000,
      requestPersistent: false,
      persistentPollingInterval: 5000,
      min: 0,
      max: 100,
      step: 1,
      decimals: 0,
      units: '',
      showValue: true,
      showOnOffLabels: true,
      onLabel: 'ON',
      offLabel: 'OFF',
      activeColor: '#5469ff',
      inactiveColor: '#9ba2b0',
      ...copy.control,
    },
    advancedControl: {
      mode: 'actionButton' as const,
      title: '',
      buttonText: '执行',
      method: 'setState',
      params: '{}',
      requestTimeout: 5000,
      requestPersistent: false,
      pollingInterval: 1000,
      readMethod: 'getState',
      writeMethod: 'setState',
      panelColor: '#305680',
      pageSize: 10,
      allowDelete: true,
      maxLines: 100,
      actionMode: 'none' as const,
      actionTarget: '',
      leftLabel: 'Traditional',
      rightLabel: 'Hi-Perf',
      initialValue: false,
      onLabel: 'Opened',
      offLabel: 'Closed',
      onColor: '#3f52dd',
      offColor: '#ffffff',
      attributeScope: 'SERVER_SCOPE' as const,
      attributesJson: '{}',
      isConnector: false,
      ...copy.advancedControl,
      pins: copy.advancedControl?.pins?.map((pin) => ({ ...pin })) || [],
    },
    input: {
      widgetMode: 'ATTRIBUTE' as const,
      attributeScope: 'SERVER_SCOPE' as const,
      showLabel: true,
      showResultMessage: true,
      required: true,
      label: '',
      showTimeInput: false,
      min: null,
      max: null,
      displayPreview: true,
      displayClearButton: false,
      displayApplyButton: true,
      displayDiscardButton: true,
      ...copy.input,
    },
    locationInput: {
      latKeyName: 'latitude',
      lngKeyName: 'longitude',
      showGetLocation: true,
      enableHighAccuracy: false,
      showLabel: true,
      showResultMessage: true,
      latLabel: '',
      lngLabel: '',
      inputFieldsAlignment: 'column' as const,
      isLatRequired: true,
      isLngRequired: true,
      requiredErrorMessage: '',
      ...copy.locationInput,
    },
    photoInput: {
      saveToGallery: true,
      usePublicGalleryLink: false,
      imageFormat: 'image/png' as const,
      imageQuality: 0.92,
      maxWidth: 640,
      maxHeight: 480,
      ...copy.photoInput,
    },
    ledIndicator: {
      title: 'Led indicator',
      ledColor: '#4caf50',
      initialValue: false,
      valueAttribute: 'value',
      retrieveValueMethod: 'attribute' as const,
      attributeScope: 'SERVER_SCOPE' as const,
      parseValueFunction: 'return data ? true : false;',
      performCheckStatus: true,
      checkStatusMethod: 'checkStatus',
      requestTimeout: 500,
      requestPersistent: false,
      persistentPollingInterval: 5000,
      ...copy.ledIndicator,
    },
    multiInput: {
      showResultMessage: true,
      showActionButtons: true,
      updateAllValues: false,
      saveButtonLabel: '',
      resetButtonLabel: '',
      showGroupTitle: false,
      groupTitle: '',
      fieldsAlignment: 'row' as const,
      fieldsInRow: 2,
      rowGap: 5,
      columnGap: 10,
      ...copy.multiInput,
    },
    count: {
      kind: 'entity' as const,
      entityType: 'DEVICE' as const,
      nameFilter: '',
      statusList: ['ACTIVE' as const],
      severityList: [],
      typeList: '',
      timeWindowMs: 0,
      label: 'Devices',
      showLabel: true,
      layout: 'column' as const,
      showIcon: true,
      icon: 'devices',
      iconSize: 20,
      iconColor: '#fff',
      iconBackgroundColor: '#f18d17',
      showIconBackground: true,
      valueColor: '#eaf5ff',
      valueFontSize: 20,
      ...copy.count,
    },
    attributeCard: {
      showSourceTitle: true,
      labelWidth: 30,
      showMissing: true,
      ...copy.attributeCard,
    },
    alarmTable: {
      enableSelection: false,
      enableSearch: true,
      enableFilter: true,
      displayDetails: true,
      displayPagination: true,
      defaultPageSize: 10,
      defaultSortOrder: 'DESC' as const,
      statusList: [],
      severityList: [],
      useTimeWindow: false,
      allowAcknowledgment: true,
      allowClear: true,
      ...copy.alarmTable,
    },
    deviceClaim: {
      deviceSecret: true,
      showLabel: true,
      deviceLabel: '设备名称',
      secretKeyLabel: '密钥',
      claimButtonLabel: '认领设备',
      successfulClaimDevice: '设备认领成功',
      failedClaimDevice: '设备认领失败',
      ...copy.deviceClaim,
    },
    entityHierarchy: {
      relationType: 'Contains',
      direction: 'FROM' as const,
      maxDepth: 3,
      showEntityType: true,
      sortByName: true,
      expandRoot: true,
      ...copy.entityHierarchy,
    },
    entityTable: {
      entityType: 'DEVICE' as const,
      enableSearch: true,
      displayPagination: true,
      pageSize: 10,
      sortOrder: 'ASC' as const,
      showLabel: true,
      showType: true,
      stickyHeader: true,
      columns: [],
      adminMode: false,
      allowCreate: false,
      allowEdit: false,
      allowDelete: false,
      editLocation: false,
      ...copy.entityTable,
    },
    aggregate: { showChart: true, showSubtitle: true, subtitle: '${entityName}', slots: [], ...copy.aggregate },
    liquid: {
      shape: 'Vertical Cylinder',
      layout: 'percentage' as const,
      datasourceUnits: '%',
      capacity: 500,
      capacityUnits: 'L',
      displayUnits: 'L',
      tankColor: { color: '#242770', ranges: [] },
      liquidColor: { color: '#7A8BFF', ranges: [] },
      valueColor: { color: '#dae9f6', ranges: [] },
      backgroundOverlayColor: { color: 'rgba(255,255,255,.16)', ranges: [] },
      volumeColor: '#bcd0df',
      volumeFontSize: 14,
      showOverlay: true,
      animation: true,
      showTooltip: true,
      showTooltipDate: true,
      tooltipUnits: '%',
      tooltipDecimals: 1,
      bindings: {},
      ...copy.liquid,
    },
    radial: {
      min: null,
      max: null,
      startAngle: 90,
      splitNumber: 5,
      showAxisLabels: true,
      showTickLabels: false,
      shape: 'polygon' as const,
      normalizeAxes: false,
      color: '#3F52DD',
      showLine: true,
      lineWidth: 2,
      lineType: 'solid' as const,
      showPoints: true,
      pointSize: 4,
      pointShape: 'circle' as const,
      fillArea: false,
      areaOpacity: 0.4,
      barWidth: 100,
      ...copy.radial,
    },
  };
}

export function nativeSeriesSettings(key: TbDataKey, native: NativeOptions): NativeSeriesSettings {
  return {
    type: native.family === 'bar' ? 'bar' : native.chartType,
    lineWidth: 2,
    smooth: false,
    step: false,
    showPoints: false,
    pointSize: 6,
    area: native.family === 'range',
    axisId: 'default',
    hidden: false,
    showLabel: native.family === 'bar',
    ...JSON.parse(JSON.stringify(key.settings?.native || {})),
    ...(native.family === 'range' ? { type: 'line' as const } : {}),
    ...(native.family === 'state' ? { type: 'line' as const, smooth: false, step: 'end' as const } : {}),
  };
}

export function nativeTimestamp(ts: number, format: string = 'locale', now = Date.now()): string {
  if (!Number.isFinite(ts) || ts < 0) return '更新时间未知';
  const date = new Date(ts);
  if (format === 'relative') {
    const seconds = Math.max(0, Math.floor((now - ts) / 1000));
    return seconds < 60
      ? `${seconds} 秒前`
      : seconds < 3600
        ? `${Math.floor(seconds / 60)} 分钟前`
        : `${Math.floor(seconds / 3600)} 小时前`;
  }
  if (format === 'iso') return date.toISOString();
  if (format === 'date') return date.toLocaleDateString();
  if (format === 'time') return date.toLocaleTimeString();
  return date.toLocaleString();
}
